### ISSUE TITLE
Bricks server

### ISSUE THREAD

**Issue by modderongithub** [SwiftKraft/SwiftNPCs#4]
When I install the plugin and the API, the server bricks during boot. Almost never gets past the silent heartbeat, and never gets to "Waiting for players..."

**Comment by modderongithub** [comment]
(Using NWAPI, not EXILED)

**Comment by SwiftKraft** [comment]
Did you add SwiftAPI and harmony? They need these two dependencies

**Comment by modderongithub** [comment]
Ah, didn't add harmony. Will try now.

**Comment by modderongithub** [comment]
Works now, thanks. Maybe mention needing harmony in the github description though, others probably run into the same issue as me. Closing now.
