### ISSUE TITLE
Error in some ai

### ISSUE THREAD

**Issue by minion6011** [SwiftKraft/SwiftNPCs#5]
- Scp 049 follow player but does not attack
- Scp 106 follow player but does not attack
- Scp 096 does not trigger when you look at him and does not attack or follow player
- class-d bugs on the stairs of gate A in surface 
- I suggest to add the option to set custom names to the ai

**Comment by SwiftKraft** [comment]
These are not errors or bugs, they are unimplemented features. The gate A stairs is a limitation/issue with the map or navmesh.

**Comment by minion6011** [comment]
ok thanks
